CREATE SCHEMA IF NOT EXISTS secureapp;

SET NAMES 'UTF8MB4';
SET TIME_ZONE = 'US/EASTERN';

USE secureapp;

DROP TABLE IF EXIST Users;

CREATE TABLE Users(

    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(30) DEFAULT NULL,
    title VARCHAR(50) DEFAULT NULL,
    bio VARCHAR(255) DEFAULT NULL,
    enable BOOLEAN DEFAULT FALSE,
    non_locked BOOLEAN DEFAULT TRUE,
    using_mfa BOOLEAN DEFAULT FALSE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    image_url VARCHAR(255) DEFAULT 'https://cdn-icons-png.flaticon.com/128/149/149071.png',
    constraint UQ_Users_Email UNIQUE (email)

);

DROP TABLE IF EXIST Roles;

CREATE Roles(

    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    permission  VARCHAR(255) NOT NULL,

    constraint UQ_Roles_Name UNIQUE (name)

);

DROP TABLE IF EXIST UserRoles;

CREATE UserRoles(

    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT UNSIGNED NOT NULL,
    role_id     BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCE Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (role_id) REFERENCE Roles (id) ON DELETE CASCADE ON UPDATE CASCADE,
    constraint UQ_UserRoles_user_id UNIQUE (user_id)


);
DROP TABLE IF EXIST Events;

CREATE Events(

    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type        VARCHAR(50) NOT NULL CHECK(type IN ('LOGIN_ATTEMPT',
       'LOGIN_ATTEMPT_FAILURE', 'LOGIN_ATTEMPT)_SUCCESS',
       'PROFILE_UPDATE', 'PROFILE_PICTURE_UPDATE', 'ROLE_UPDATE',
       'ACCOUNT_SETTINGS_UPDATE', 'PASSWORD_UPDATE', 'MFA_UPDATE')),
    description  VARCHAR(255) NOT NULL,

    constraint UQ_Events_type UNIQUE (type)

);

DROP TABLE IF EXIST UserEvents;

CREATE UserEvents(

    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT UNSIGNED NOT NULL,
    event_id     BIGINT UNSIGNED NOT NULL,
    device VARCHAR(100) DEFAULT NULL,
    ip_address VARCHAR(100) DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCE Users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (event_id) REFERENCE Events (id) ON DELETE CASCADE ON UPDATE CASCADE,


);



